stages:
    - build
    - test

default:
    image: 'gcc'

build:
    before_script:
        - apt-get update --yes
        - apt-get install --yes cmake
    script: 
        - make
    after_script: 
        - make destroy